### ISSUE TITLE
Plugin breaks when markdown contains < or > 

### ISSUE THREAD

**Issue by gertdreyer** [geekris1/vite-plugin-react-markdown#2]
The plugin does not transform < and > to legal JSX. 

Please see:
https://codesandbox.io/p/sandbox/throbbing-water-zcxqs6?file=%2Fsrc%2Ftest.md%3A6%2C32

**Comment by geekris1** [comment]
I have fixed it, and you can pass the latest version 0.2.10.

https://github.com/geekris1/vite-plugin-react-markdown/commit/2267d95b99454b816952c3588c7c8b811884ad37
